---

- name: 'Install postgresql'
  package:
    name: postgresql
    state: latest

- find:
    path: '{{ pg_data_dir }}'
    patterns: "*"
  register: find_pg_data_dir

- name: 'Init postgresql'
  command: initdb --encoding UTF8 --pgdata '{{ pg_data_dir }}'
  become: yes
  become_user: postgres
  when: find_pg_data_dir.matched|int == 0

- name: 'Enable and start postgresql'
  service:
    name: postgresql
    state: started
    enabled: yes
    daemon_reload: yes
