---

- name: 'Install nginx'
  package:
    name: nginx
    state: latest

- name: 'Create directories'
  file:
    path: '{{ item }}'
    state: directory
    mode: 0700
  with_items:
    - /etc/nginx
    - /etc/nginx/conf.d

- name: 'Set configuration files'
  copy:
    src: '{{ item }}'
    dest: '/etc/nginx/{{ item }}'
    owner: root
    group: root
    mode: 0600
  with_items:
    - nginx.conf
    - letsencrypt.conf
    - conf.d/non-ssl-redirect.conf
  notify:
    - restart nginx

- name: 'Set configuration templates'
  template:
    src: '{{ item }}.j2'
    dest: '/etc/nginx/{{ item }}'
    owner: root
    group: root
    mode: 0600
  with_items:
    - ssl.conf
  notify:
    - restart nginx

- name: 'Enable & Start nginx'
  service:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes
