---

- name: 'Install php-fpm'
  package:
    name: php-fpm
    state: latest

- name: 'Enable and start php-fpm'
  service:
    name: php-fpm
    state: started
    enabled: yes
    daemon_reload: yes
