galaxy_info:
  author: Maxime “pep” Buquet
  description: Nginx
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Archlinux
    versions:
    - all
  galaxy_tags:
  - nginx
  - webserver

dependencies:
- { role: ssl-certs }
