---

- name: 'Clear previous movim-git builds'
  file:
    state: absent
    path: /tmp/packages/movim-git

- name: 'Prepare packages directory'
  file:
    state: directory
    recurse: yes
    path: /tmp/packages
    owner: makepkg

- name: 'Install dependencies'
  package:
    name: php-pgsql
    state: latest

- name: 'Download php-imagick package'
  unarchive:
    src: https://aur.archlinux.org/cgit/aur.git/snapshot/php-imagick.tar.gz
    dest: /tmp/packages
    remote_src: yes
    owner: makepkg

- name: 'Install php-imagick'
  command: makepkg --syncdeps --force --install --asdeps --noconfirm
  args:
    chdir: /tmp/packages/php-imagick
  become: true
  become_user: makepkg

- name: 'Download movim-git package'
  unarchive:
    src: https://aur.archlinux.org/cgit/aur.git/snapshot/movim-git.tar.gz
    dest: /tmp/packages
    remote_src: yes
    owner: makepkg

- name: 'Build movim-git'
  command: makepkg --syncdeps --force --install --noconfirm
  args:
    chdir: /tmp/packages/movim-git
  become: true
  become_user: makepkg

- name: 'Install movim.nginx'
  template:
    src: movim.nginx.j2
    dest: /etc/nginx/conf.d/movim.conf
    owner: root
    group: root
    mode: 0640
  notify: reload nginx

- name: 'Create postgresql database'
  postgresql_db:
    name: '{{ db_name }}'
    state: present
    encoding: UTF-8

- name: 'Create postgresql user'
  postgresql_user:
    db: '{{ db_name }}'
    name: '{{ db_user }}'
    password: '{{ db_passwd }}'

- name: 'Install movim configuration'
  template:
    src: movim.conf.j2
    dest: /etc/webapps/movim/db.inc.php
    owner: root
    group: http
    mode: 0640

- name: 'Install movim daemon configuration'
  template:
    src: movim.default.j2
    dest: /etc/default/movim
    owner: root
    group: http
    mode: 0640
  notify: restart movim

- name: 'Install movim.php-fpm.conf'
  copy:
    src: movim.php-fpm
    dest: /etc/php/php-fpm.d/movim.conf
  notify: reload php-fpm

- name: 'Enable and Start movim'
  service:
    name: movim
    enabled: yes
    daemon_reload: yes
