---

- name: 'Install base & base-devel'
  pacman:
    name: base base-devel
    state: latest
    update_cache: yes

- name: 'Create makepkg user'
  user:
    name: makepkg
    state: present
    system: yes

- name: 'Sudo perms for makepkg'
  copy:
    src: makepkg.sudoers
    dest: /etc/sudoers.d/makepkg
    owner: root
    group: root
    mode: 0400
